spring:
  application:
    name: skapp
  datasource:
    url: 'jdbc:mysql://localhost:3306/skapptest?createDatabaseIfNotExist=true'
    username: root
    password: Akila@1997
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    generate-ddl : true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        ddl-auto: update
        show_sql: true
        format_sql: true
